name: DiamondEconomy
version: 1.1.0
main: com.mikey1201.DiamondEconomy
api-version: 1.20
author: mikey1201
softdepend: [Vault]

commands:
  balance:
    description: Check your balance or another player's balance.
    usage: /<command> [player]
    aliases: [bal, money]
  deposit:
    description: Deposit physical currency items.
    usage: /<command> <amount|all>
  withdraw:
    description: Withdraw physical currency items.
    usage: /<command> <amount|all>
  pay:
    description: Pay another player.
    usage: /<command> <player> <amount>
  baltop:
    description: View the top balances.
    usage: /<command> [toggle]
  eco:
    description: Manage the economy.
    usage: /<command> <give|take|set> <player> <amount>
  diamondeconomy:
    description: Main plugin command.
    usage: /<command> [reload]
    aliases: [de]