name: DiamondEconomy
version: 1.0.2
main: com.mikey1201.DiamondEconomy
api-version: '1.18'
author: mikey1201
description: A lightweight, diamond-based economy plugin using Vault.
depend: [Vault]
folia-supported: true

commands:
  balance:
    description: Check your balance or another player's balance.
    usage: /<command> [player]
    aliases: [bal, money]
  eco:
    description: Manage the economy.
    usage: /<command> <give|take|set> <player> <amount>
    permission: diamondeconomy.admin
  deposit:
    description: Deposits diamonds from your inventory into your account.
    usage: /<command> <amount|all>
    aliases: [dep, depo]
  withdraw:
    description: Withdraws diamonds from your account to your inventory.
    usage: /<command> <amount|all>
    aliases: [wit, with]
  pay:
    description: Pays another player from your balance.
    usage: /<command> <player> <amount>
  baltop:
    description: Shows the players with the highest balances.
    usage: /<command>
    aliases: [top, balancetop]