name: DiamondEconomy
version: 1.2.2
main: com.mikey1201.DiamondEconomy
api-version: 1.21
author: mikey1201
softdepend: [Vault]

commands:
  balance:
    description: Check your balance or another player's balance.
    usage: /<command> [player]
    aliases: [bal]
  deposit:
    description: Deposit physical currency items.
    usage: /<command> <amount|all>
    aliases: [depo]
  withdraw:
    description: Withdraw physical currency items.
    usage: /<command> <amount|all>
    aliases: [with]
  pay:
    description: Pay another player.
    usage: /<command> <player> <amount>
  baltop:
    description: View the top balances.
    usage: /<command> [toggle]
  eco:
    description: Manage the economy.
    usage: /<command> <give|take|set> <player> <amount>
  diamondeconomy:
    description: Main plugin command.
    usage: /<command> [reload]
    aliases: [de]

permissions:
  diamondeconomy.use:
    description: Allows use of basic economy commands.
    default: true
  diamondeconomy.balance.others:
    description: Allows checking other players' balances.
    default: op
  diamondeconomy.toggle:
    description: Allows toggling visibility in /baltop.
    default: true
  diamondeconomy.admin:
    description: Allows use of all admin commands (eco, reload).
    default: op
    children:
      diamondeconomy.use: true
      diamondeconomy.balance.others: true
